application: bafghahi-website
version: 1-1-beta
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/menthas_pw/favicon.ico
  upload: static/menthas_pw/favicon\.ico
- url: /static
  static_dir: static
- url: .*
  script: pw_django.wsgi.application

libraries:
- name: django
  version: 1.5
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: "latest"
- name: ssl
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'pw_django.settings'
  DATABASE_URL: 'mysql://root@bafghahi-website:pw/blog'
