# code generated by Appengine Toolkit
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), 'libs'))
# end generated code


class VirtualModule(object):
    def __init__(self, name):
        import sys
        sys.modules[name] = self

    def __getattr__(self, name):
        return globals()[name]
VirtualModule("__main__")
